#! /bin/bash

# This script copies the libraries and header files into the LitePipeTestApp
# project. 
#
# Ths list of required header files was obtained via the ViM checkpaths
# (Li) command
# TestMediaPlayer.cpp
#
#   - Created a script to set the include path and execute the check,
#
#   set path +=.
#   set path +=../../../OhNet/Build/Include
#   set path +=../../../LitePipe
#   set path +=../../../LitePipe/OpenHome/Av/Tests
#   Li
#
#   - Execute from the command line piping to file for further processing
#     NB Make the terminal wide enough to avoid line wrapping.
#
#     vim -S <script file> | tee <output file>
#

TEST_APP=$CVS_VIEWS/TestAppsTidied/Win32

IncludeDirs="
Include/OpenHome
Include/OpenHome/Av
Include/OpenHome/Av/Songcast
Include/OpenHome/Av/Tests
Include/OpenHome/Av/UpnpAv
Include/OpenHome/Av/Utils
Include/OpenHome/Configuration
Include/OpenHome/Configuration/Tests
Include/OpenHome/Media
Include/OpenHome/Media/Codec
Include/OpenHome/Media/Pipeline
Include/OpenHome/Media/Protocol
Include/OpenHome/Media/Tests
Include/OpenHome/Media/Utils
Include/OpenHome/Net
Include/OpenHome/Net/C
Include/OpenHome/Net/Core
Include/OpenHome/Net/Private
Include/OpenHome/Private"

pushd $TEST_APP

for i in $IncludeDirs
do
  echo $i
  if [ ! -e "$i" ]
  then
    mkdir -p "$i"
  fi
done

if [ ! -e Libs ]
then
  mkdir "Libs"
fi

popd

# Make sure the required 
# Copy libraries into our tree

echo "Copying Libraries into project ....."

cp $CVS_VIEWS/LitePipe/build/CodecAac.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAacBase.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAdts.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAifc.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAiff.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAiffBase.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAlac.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecAlacBase.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecFlac.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecPcm.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecVorbis.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/CodecWav.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/SourcePlaylist.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/SourceSongCast.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/SourceUpnpAv.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/dependencies/Windows-x86/openssl/lib/lib.pdb $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/libOgg.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/dependencies/Windows-x86/openssl/lib/libeay32.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/ohMediaPlayer.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/build/ohMediaPlayerTestUtils.lib $TEST_APP/Libs
cp $CVS_VIEWS/OhNet/Build/Obj/Windows/Debug/ohNetCore.lib $TEST_APP/Libs
cp $CVS_VIEWS/OhNetMon/build/ohNetmon.lib $TEST_APP/Libs
cp $CVS_VIEWS//LitePipe/build/ohPipeline.lib $TEST_APP/Libs
cp $CVS_VIEWS/LitePipe/dependencies/Windows-x86/openssl/lib/ssleay32.lib $TEST_APP/Libs
#cp $CVS_VIEWS/OhNet/Build/Obj/Windows/Debug/Shell.lib $TEST_APP/Libs
#cp $CVS_VIEWS/LitePipe/build/SourceRadio.lib $TEST_APP/Libs
#cp $CVS_VIEWS/LitePipe/build/SourceRaop.lib $TEST_APP/Libs
#cp $CVS_VIEWS/OhNet/Build/Obj/Windows/Debug/TestFramework.lib $TEST_APP/Libs

# Copy include files into our tree

echo "Copying Include Files into project ....."

cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Types.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/OsTypes.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Defines.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Buffer.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Exception.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Os.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/OsWrapper.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/OsWrapper.inl $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Standard.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Buffer.inl $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/LitePipe/OpenHome/Av/MediaPlayer.h $TEST_APP/Include/OpenHome/Av
cp $CVS_VIEWS/LitePipe/OpenHome/Media/MuteManager.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Thread.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Functor.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/LitePipe/OpenHome/Media/VolumeManager.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/LitePipe/OpenHome/PowerManager.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Core/DvDevice.h $TEST_APP/Include/OpenHome/Net/Core
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Core/DvResourceWriter.h $TEST_APP/Include/OpenHome/Net/Core
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Core/OhNet.h $TEST_APP/Include/OpenHome/Net/Core
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Core/FunctorAsync.h $TEST_APP/Include/OpenHome/Net/Core
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/FunctorMsg.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/FunctorNetworkAdapter.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/C/OhNet.h $TEST_APP/Include/OpenHome/Net/C
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/C/Async.h $TEST_APP/Include/OpenHome/Net/C
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Utils/DriverSongcastSender.h $TEST_APP/Include/OpenHome/Av/Utils
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Msg.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Fifo.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Stream.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/LitePipe/OpenHome/Media/InfoProvider.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Shell.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Network.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Env.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Utils/ProcessorPcmUtils.h $TEST_APP/Include/OpenHome/Media/Utils
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/OhmSender.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Timer.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Queue.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Http.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Ascii.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Uri.h  $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/ZoneHandler.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/Ohm.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/OhmMsg.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/OhmSocket.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Songcast/OhmSenderDriver.h $TEST_APP/Include/OpenHome/Av/Songcast
cp $CVS_VIEWS/LitePipe/OpenHome/Media/PipelineManager.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/LitePipe/OpenHome/Media/PipelineObserver.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/SpotifyReporter.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/AudioReservoir.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Reporter.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Printer.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Debug.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Codec/CodecFactory.h $TEST_APP/Include/OpenHome/Media/Codec
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Protocol/ProtocolFactory.h $TEST_APP/Include/OpenHome/Media/Protocol
cp $CVS_VIEWS/LitePipe/OpenHome/Av/SourceFactory.h $TEST_APP/Include/OpenHome/Av
cp $CVS_VIEWS/LitePipe/OpenHome/Av/KvpStore.h $TEST_APP/Include/OpenHome/Av
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Tests/RamStore.h $TEST_APP/Include/OpenHome/Av/Tests
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Tests/VolumeUtils.h  $TEST_APP/Include/OpenHome/Media/Tests
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/OhNetTypes.h $TEST_APP/Include/OpenHome
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviStack.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviServerUpnp.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviDevice.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviService.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Service.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/FunctorDviInvocation.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviSubscription.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Core/DvInvocationResponse.h $TEST_APP/Include/OpenHome/Net/Core
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Subscription.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviServer.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviServerWebSocket.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Bonjour.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviPropertyUpdateCollection.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviSsdpNotifier.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviProtocolUpnp.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Discovery.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/Ssdp.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/DviServerLpec.h $TEST_APP/Include/OpenHome/Net/Private
cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/Parser.h $TEST_APP/Include/OpenHome/Private
cp $CVS_VIEWS/LitePipe/OpenHome/Av/UpnpAv/UpnpAv.h $TEST_APP/Include/OpenHome/Av/UpnpAv
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Source.h $TEST_APP/Include/OpenHome/Av
cp $CVS_VIEWS/LitePipe/OpenHome/Configuration/ConfigManager.h $TEST_APP/Include/OpenHome/Configuration
cp $CVS_VIEWS/LitePipe/OpenHome/Configuration/BufferPtrCmp.h $TEST_APP/Include/OpenHome/Configuration
cp $CVS_VIEWS/LitePipe/OpenHome/Configuration/IStore.h $TEST_APP/Include/OpenHome/Configuration
cp $CVS_VIEWS/LitePipe/OpenHome/Configuration/Tests/ConfigRamStore.h $TEST_APP/Include/OpenHome/Configuration/Tests
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Utils/IconDriverSongcastSender.h $TEST_APP/Include/OpenHome/Av/Utils
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Debug.h $TEST_APP/Include/OpenHome/Media
cp $CVS_VIEWS/LitePipe/OpenHome/Av/Debug.h $TEST_APP/Include/OpenHome/Av
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Pipeline.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/EncodedAudioReservoir.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Codec/Container.h $TEST_APP/Include/OpenHome/Media/Codec
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Codec/CodecController.h $TEST_APP/Include/OpenHome/Media/Codec
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Rewinder.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/TimestampInspector.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/DecodedAudioAggregator.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/DecodedAudioReservoir.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Seeker.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/VariableDelay.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/TrackInspector.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Skipper.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Waiter.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Stopper.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Ramper.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Gorger.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Router.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Pruner.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/Logger.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/SampleRateValidator.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/StarvationMonitor.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Pipeline/PreDriver.h $TEST_APP/Include/OpenHome/Media/Pipeline
cp $CVS_VIEWS/LitePipe/OpenHome/Media/ClockPuller.h $TEST_APP/Include/OpenHome/Media
#cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/OptionParser.h $TEST_APP/Include/OpenHome/Private
#cp $CVS_VIEWS/LitePipe/OpenHome/Media/UriProviderSingleTrack.h $TEST_APP/Include/OpenHome/Media
#cp $CVS_VIEWS/LitePipe/OpenHome/Media/Filler.h $TEST_APP/Include/OpenHome/Media
#cp $CVS_VIEWS/LitePipe/OpenHome/Media/Protocol/Protocol.h $TEST_APP/Include/OpenHome/Media/Protocol
#cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Net/Private/ShellCommandDebug.h $TEST_APP/Include/OpenHome/Net/Private
#cp $CVS_VIEWS/LitePipe/OpenHome/Av/Credentials.h $TEST_APP/Include/OpenHome/Av
#cp $CVS_VIEWS/OhNet/Build/Include/OpenHome/Private/TestFramework.h $TEST_APP/Include/OpenHome/Private

echo "Copying Extra Include Files (for TestMediaPlayerMain.cpp)  ....."

#cp $CVS_VIEWS/LitePipe/OpenHome/Media/Tests/Cdecl.h $TEST_APP/Include/OpenHome/Media/Tests
#cp $CVS_VIEWS/LitePipe/OpenHome/Media/Tests/GetCh.h $TEST_APP/Include/OpenHome/Media/Tests
cp $CVS_VIEWS/LitePipe/OpenHome/Media/Utils/DriverBasic.h $TEST_APP/Include/OpenHome/Media/Utils

echo "NO Extra Libraries Required (for TestMediaPlayerMain.cpp)"
